"""empty message

Revision ID: 4f89bde13817
Revises: 6a481ce5d140
Create Date: 2026-04-02 22:37:18.434216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f89bde13817'
down_revision = '6a481ce5d140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('urgent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('urgent')
        batch_op.drop_column('hours')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
